### ISSUE TITLE
Setting qjit keep_intermediate=True flag leads to memory corruptions

### ISSUE THREAD

**Issue by grwlf** [PennyLaneAI/catalyst#291] opened 2023-09-28 10:58 UTC
Changing `@qjit` to `@qjit(keep_intermediate=True)` in some tests leads to memory corruptions (seen as mismatched test results).

This behavior was observed in [test_adjoint.py](https://github.com/PennyLaneAI/catalyst/blob/422dc14879071039a9a64eb781627b6b441174de/frontend/test/pytest/test_adjoint.py#L37), [test_gradient.py](https://github.com/PennyLaneAI/catalyst/blob/422dc14879071039a9a64eb781627b6b441174de/frontend/test/pytest/test_gradient.py#L155) and in some others.

The affected Catalyst revision is 422dc148

**Comment by dime10** [comment] 2023-09-28 14:35
Thanks for reporting this! Assuming this stems from the new C++ compiler driver, the memory sanitizers might be able to help debug the issue. Hopefully #196 will get merged soon.

**Comment by erick-xanadu** [comment] 2023-09-28 15:45
This issue has not to do with C++, but different pytest threads sharing the folder with the shared object and different IRs (if run in parallel). If they are not run in parallel, a similar issue comes up. I believe that the shared object is not rewritten or something similar. If each folder has a unique name, the issue is resolved:

```diff
diff --git a/frontend/catalyst/compiler.py b/frontend/catalyst/compiler.py
index d987aed..834f522 100644
--- a/frontend/catalyst/compiler.py
+++ b/frontend/catalyst/compiler.py
@@ -309,6 +309,7 @@ class LinkerDriver:
         msg += "compiler was found by Catalyst, please specify a compatible one via $CATALYST_CC."
         raise CompileError(msg)
 
+GLOBAL_ID = 0
 
 class Compiler:
     """Compiles MLIR modules to shared objects by executing the Catalyst compiler driver library."""
@@ -346,9 +347,11 @@ class Compiler:
                ret_type_name (str) Inferred main function result type name
         """
         pipelines = pipelines if pipelines is not None else DEFAULT_PIPELINES
+        global GLOBAL_ID
         if self.options.keep_intermediate:
-            workspace = os.path.abspath(os.path.join(os.getcwd(), module_name))
+            workspace = os.path.abspath(os.path.join(os.getcwd(), module_name + str(GLOBAL_ID)))
             os.makedirs(workspace, exist_ok=True)
+            GLOBAL_ID += 1
         else:
             # pylint: disable=consider-using-with
             if self.last_tmpdir:
diff --git a/frontend/test/pytest/test_adjoint.py b/frontend/test/pytest/test_adjoint.py
index a8b1fed..3b157a5 100644
--- a/frontend/test/pytest/test_adjoint.py
+++ b/frontend/test/pytest/test_adjoint.py
@@ -34,7 +34,7 @@ def verify_catalyst_adjoint_against_pennylane(quantum_func, device, *args):
     its adjoint computed.
     """
 
-    @qjit
+    @qjit(keep_intermediate=True)
     @qml.qnode(device)
     def catalyst_workflow(*args):
         C_adjoint(quantum_func)(*args)

```

```
(env) erick.ochoalopez@DL7420-GS4N1J3:~/Code/catalyst-latest$ !pyt
pytest frontend/test/pytest/test_adjoint.py 
=================================================================================== test session starts ===================================================================================
platform linux -- Python 3.10.11, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/erick.ochoalopez/Code/catalyst-latest/frontend/test/pytest
configfile: pytest.ini
plugins: xdist-3.3.1, nbmake-1.4.3, cov-4.1.0
collected 21 items                                                                                                                                                                        

frontend/test/pytest/test_adjoint.py .....................                                                                                                                          [100%]

```

**Comment by erick-xanadu** [comment] 2023-09-28 15:46
I will try to come up with a clean solution :) but also working on other things at the moment. Thanks for reporting @grwlf !

**Comment by grwlf** [comment] 2023-09-28 16:39
@erick-xanadu - great guess! I am pretty sure that on my machine I do not have `pytest_xdist` installed and tests run consequently, but shared folder is a weak spot indeed. Thanks for the patch, I'll give it a try next week.

**Comment by grwlf** [comment] 2023-10-02 12:42
FYI: I have checked the patch, it works for me.

**Closed** 2023-10-12 03:15 UTC
Labels: bug
