### ISSUE TITLE
Propagate QNode tag in parameter shift transform

### ISSUE THREAD

**Issue by dime10** [PennyLaneAI/catalyst#427] opened 2024-01-04 16:10 UTC
Some MLIR transforms, like the parameter shift pass, predate the introduction of the `qnode` attribute on MLIR functions with quantum code. The use of the attribute has also been extended, for example to determine asynchronous execution scopes.

In order to support the asynchronous execution of shifted circuits, the parameter-shift transform should propagate the `qnode` attribute from the original function it acts upon to the shifted function calls which each represent an independent quantum execution.

Note I don't think the current implementation would be able to benefit much from asynchronous execution, except perhaps for two evaluations at a time, because the shifted circuits are not generated in a batched but a procedural fashion. See the following snippet, where the results a quantum call a used pretty much immediately: 

https://github.com/PennyLaneAI/catalyst/blob/b94be65521c726eb231dc9a42f00645757bd804b/mlir/lib/Gradient/Transforms/GradMethods/PS_QuantumGradient.cpp#L78-L91

**Comment by erick-xanadu** [comment] 2024-01-04 16:18
Duplicate of #419

**Closed** 2024-01-05 11:29 UTC
Labels: enhancement, compiler
