### ISSUE TITLE
[Frontend] Late result type unification in catalyst.cond during the quantum tracing

### ISSUE THREAD

**Issue by grwlf** [PennyLaneAI/catalyst#403] opened 2023-12-14 10:35 UTC
This is a potential issue which was discovered during the Jax dynamic API development. In the two-stage quantum tracing, we do the type unification of all the conditional branches _after_ user transformations are applied. That means, that during the quantum-tape transformations, users will see a non-unified result type which happens to be the result type of the last branch of the conditional statement.

In order to fix this issue, we suggest to do the type unification both before and after applying user quantum-tape transformations. See the following [fixme](https://github.com/PennyLaneAI/catalyst/blob/519536e77e1217b8e6686e4abe2dc23ffe702b57/frontend/catalyst/pennylane_extensions.py#L1312) in the development branch

**Comment by dime10** [comment] 2024-06-24 17:10
duplicate of https://github.com/PennyLaneAI/catalyst/issues/824

**Closed** 2024-06-24 17:10 UTC
